# File to write log to.
logFile: test.log

# Log level.
# It can be one of DEBUG, INFO, WARNING and ERROR.
logLevel: INFO

# Whether to print log to screen.
logToStdErr: true

# Whether to forward MQTT messages to TCP brokers.
crossForward: false

# Message processing functions.
# A message will go through these functions one by one.
sqlFiles:
- "etc/sql.txt"

# Brokers. Each of them has following fields:
# 1. brokerName: Name of the broker. It is a unique identifier of a broker.
# 2. brokerURI: URI of the broker that the bridge will connect to.
# 3. connectType: Type of connection of this broker. It can be one of MQTTConnection and TCPConnection.
# 4. brokerSubs: Topic list which the broker subscribes. Only messages with matched topic will be forwarded to this broker.
# 5. brokerFwds: Topic list which the broker forwards. Only messages with matched topic will be sent from this broker to the bridge.
# 6. brokerMount: Mountpoint of this broker. It will be added to the head of topic of messages that the bridge receive from the broker. This is mostly used for preventing message looping between brokers. The bridge provides no guarantee on loop-free property.
brokers:
-
  brokerName: broker1
  brokerMount: 'mountpoint_home/'
  brokerURI: mqtt://localhost:1883/mqtt
  brokerFwds:
  - 'home/room/temp'
  brokerSubs:
  - 'mountpoint_office/mountpoint_on_recv_office/office/+'
  connectType: MQTTConnection

-
  brokerName: broker2
  brokerMount: 'mountpoint_office/'
  brokerURI: mqtt://localhost:1885/mqtt
  brokerFwds:
  - 'office/light'
  brokerSubs:
  - 'mountpoint_home/home/#'
  connectType: MQTTConnection

-
  brokerName: broker3
  brokerMount: 'mountpoint_tcp3/'
  brokerURI: tcp://localhost:19192
  brokerFwds:
  - 'tcp/#'
  brokerSubs:
  - 'home/+/temp'
  - 'mountpoint_tcp4/#'
  - 'mountpoint_home/#'
  connectType: TCPConnection

-
  brokerName: broker4
  brokerMount: 'mountpoint_tcp4/'
  brokerURI: tcp://localhost:19193
  brokerFwds:
  - 'home/room/temp'
  - 'tcp/#'
  brokerSubs:
  - 'mountpoint_tcp3/#'
  - 'mountpoint_office/#'
  connectType: TCPConnection
